### ISSUE TITLE
内存未释放

### ISSUE THREAD

**Issue by SHRemover** [inmine/XMPlayer#1]
播放一次 内存就会增加一点，十几次之后已经从初始的40多M 增到 100多M了、
提供的demo就可以复现、

**Comment by inmine** [comment]
已解决，请下载最新demo

**Comment by SHRemover** [comment]
最新的demo XMPlayer内有许多文件都丢失了、

**Comment by inmine** [comment]
不好意思，我的过，已经解决了部分文件丢失问题

**Comment by SHRemover** [comment]
客气了，感谢提供这么实用的demo~
